### ISSUE TITLE
Switching to color mode crashes Fiji..?

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-legacy#52] opened 2014-06-11 18:13 UTC
If I use the channels tool to switch to color mode, even with images opened by non-scifio, my Fiji goes to max cpu use and dies..

**Comment by ctrueden** [comment] 2022-01-10 22:04
I tried opening the `testGRB.tif` in an up-to-date Fiji just now, and cannot reproduce. So I'm gonna close this again. This issue will be here waiting for us to reopen, should the issue ever rear up again. 😉

**Closed by ctrueden** 2022-01-10 22:04 UTC
Labels: bug
