### ISSUE TITLE
Make sure that separate Contexts get separate ImageJ 1.x "instances", even in headless mode

### ISSUE THREAD

**Issue by dscho** [imagej/imagej-legacy#72] opened 2014-07-29 18:31 UTC
This is a problem identified by introducing a second test case into the `LegacyOpenerTest`: in headless mode, and only in headless mode, the `nImages()` function reports still open images even when the context was disposed and a new one was instantiated.

**Comment by ctrueden** [comment] 2016-09-01 17:55
I tried removing the `close()` calls in `LegacyOpenerTest` test methods, to see whether this issue is still a problem. And the tests do not pass even in normal (non-headless) mode. As described, `nImages` is non-zero because the same ImageJ 1.x instance gets reused for each test.

This is really due to issue #1, which documents the fact that [this window closing code during disposal](https://github.com/imagej/imagej-legacy/blob/imagej-legacy-0.22.1/src/main/java/net/imagej/legacy/IJ1Helper.java#L217-L229) apparently doesn't work as intended.

**Closed** 2016-09-01 18:10 UTC
