### ISSUE TITLE
Add confirmation buttons to ImageJ2Options

### ISSUE THREAD

**Issue by rimadoma** [imagej/imagej-legacy#161] opened 2017-05-25 14:50 UTC
A minor grievance, but the `ImageJ2Options` dialog doesn't have the usual _OK_, _Cancel_ or other such "confirmation buttons". This sometimes catches me by surprise and interrupts my workflow. Is this because unlike other `OptionPlugins` this one is displayed in legacy mode?

**Comment by ctrueden** [comment] 2017-05-25 14:55
That is by design, and it is because it `implements Interactive`. The original reason was because we were automatically popping up that options dialog when you first downloaded and ran ImageJ2, and we did not want to block the user. I cannot recall why that was so important though, or if we still do that. If you want to fix it, I think you can just remove the `implements Interactive` from the `ImageJ2Options` class.

**Comment by ctrueden** [comment] 2017-05-25 15:57
Fixed by #162.

**Closed by ctrueden** 2017-05-25 15:57 UTC
Labels: enhancement
