### ISSUE TITLE
MacroTest:testBarePluginFromMacro fails from Maven on windows

### ISSUE THREAD

**Issue by mpinkert** [imagej/imagej-legacy#234] opened 2020-02-12 18:30 UTC
The `testBarePluginFromMacro` test under `net.imagej.legacy.MacroTest` fails to complete on Windows computers if run using Maven.  The test passes if run using the IntelliJ IDE.  This has been tested on two different Windows computers.

Here is the stack trace:

```Java
C:\Users\Michael\AppData\Local\Temp\java8602882112950017776\src\main\java\Set_Property_Test.java:1: error: package ij does not exist
import ij.IJ;
         ^
C:\Users\Michael\AppData\Local\Temp\java8602882112950017776\src\main\java\Set_Property_Test.java:2: error: package ij.gui does not exist
import ij.gui.GenericDialog;
             ^
C:\Users\Michael\AppData\Local\Temp\java8602882112950017776\src\main\java\Set_Property_Test.java:3: error: package ij.plugin does not exist
import ij.plugin.PlugIn;
                ^
C:\Users\Michael\AppData\Local\Temp\java8602882112950017776\src\main\java\Set_Property_Test.java:5: error: cannot find symbol
public class Set_Property_Test implements PlugIn {
                                          ^
  symbol: class PlugIn
4 errors
[ERROR] null
java.lang.ClassNotFoundException: Set_Property_Test
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.scijava.plugins.scripting.java.JavaEngine.compile(JavaEngine.java:228)
	at org.scijava.plugins.scripting.java.JavaEngine.eval(JavaEngine.java:136)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The test also outputs a warning which may not be related, as the warning shows up on successful runs using Maven on mac.

``` Java
Set_Property_Test not up-to-date because 1 source files are not up-to-date (C:\Users\Michael\AppData\Local\Temp\java8602882112950017776\src\main\java\Set_Property_Test.java)
Compiling 1 file in C:\Users\Michael\AppData\Local\Temp\java8602882112950017776
[-classpath, C:\Users\Michael\AppData\Local\Temp\java8602882112950017776\target\classes;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\access-bridge-64.jar;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\cldrdata.jar;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\dnsns.jar;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\jaccess.jar;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\jfxrt.jar;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\localedata.jar;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\nashorn.jar;C:\Users\Michael\.m2\repository\org\jacoco\org.jacoco.agent\0.8.4\org.jacoco.agent-0.8.4-runtime.jar;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\sunec.jar;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\sunjce_provider.jar;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\sunmscapi.jar;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\sunpkcs11.jar;C:\Users\Michael\AppData\Local\Temp\surefire4317418242938591715\surefirebooter2849597479686524529.jar;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\zipfs.jar, -d, C:\Users\Michael\AppData\Local\Temp\java8602882112950017776\target\classes, C:\Users\Michael\AppData\Local\Temp\java8602882112950017776\src\main\java\Set_Property_Test.java]
using the class path: C:\Users\Michael\AppData\Local\Temp\java8602882112950017776\target\classes;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\access-bridge-64.jar;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\cldrdata.jar;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\dnsns.jar;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\jaccess.jar;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\jfxrt.jar;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\localedata.jar;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\nashorn.jar;C:\Users\Michael\.m2\repository\org\jacoco\org.jacoco.agent\0.8.4\org.jacoco.agent-0.8.4-runtime.jar;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\sunec.jar;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\sunjce_provider.jar;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\sunmscapi.jar;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\sunpkcs11.jar;C:\Users\Michael\AppData\Local\Temp\surefire4317418242938591715\surefirebooter2849597479686524529.jar;C:\Program%20Files\Java\jdk1.8.0_211\jre\lib\ext\zipfs.jar

```

**Comment by NicoKiaru** [comment] 2020-04-24 15:55
I also have this failing test in win10.

**Comment by imagejan** [comment] 2020-04-24 18:25
@NicoKiaru thanks for linking the issue.
I'm closing this as it's a duplicate of #198.

**Closed by imagejan** 2020-04-24 18:25 UTC
